# Generated by Django 4.2.8 on 2024-01-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeAcceptTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='true', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.farmer')),
                ('tree_trans_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.treedonationtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='TreeDonationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='true', max_length=255)),
                ('comments', models.TextField(default='')),
                ('image_path', models.FilePathField(default='', path='/media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tree_accept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.treeaccepttransaction')),
            ],
        ),
    ]
