# Generated by Django 4.2.8 on 2024-01-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_treeaccepttransaction_treedonationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treedonationstatus',
            name='image_path',
            field=models.FilePathField(default='', path='media'),
        ),
        migrations.AlterField(
            model_name='treedonationstatus',
            name='status',
            field=models.CharField(default='started', max_length=255),
        ),
    ]
