# Generated by Django 4.2.8 on 2024-01-20 01:26

import app.models.tree_donation_transaction
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_treedonationstatus_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treedonationtransaction',
            name='tree_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='treedonationstatus',
            name='image_path',
            field=models.ImageField(default='', upload_to=app.models.tree_donation_transaction.get_random_name),
        ),
        migrations.AlterField(
            model_name='treedonationtransaction',
            name='status',
            field=models.CharField(default='true', max_length=255),
        ),
    ]
