# Generated by Django 4.2.8 on 2024-01-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='kathmandu', max_length=200),
        ),
    ]
